Add Authorization
unbrokable/Denis_Zhuravel_EducationPortal pull request #2
Opened 2021-05-11 12:07 UTC by unbrokable

2021-05-23 12:57 UTC, vladimir-shirmanov commented on EducationPortal/BL/Interfaces/IService.cs
> +    public interface IService<T>
что это за название, если я в коде встречу IService я не пойму что он делает, придется искать его исходник и разбираться в нем

2021-05-23 12:57 UTC, vladimir-shirmanov commented on EducationPortal/BL/Services/UserService.cs
> +        public UserService(UserRepository bd, IHasher hasher)
почему для хэшера есть интерфейс, а для репозитория нет?

2021-05-23 12:57 UTC, vladimir-shirmanov commented on EducationPortal/BL/Services/UserService.cs
> +        Validator validator = new Validator();
почему валидатор не инжектится?

2021-05-23 12:57 UTC, vladimir-shirmanov commented on EducationPortal/BL/Services/UserService.cs
> +            var user = new MapperConfiguration(i => i.CreateMap<UserDTO, User>()).CreateMapper().Map<UserDTO, User>(data);
этого тут не должно быть

2021-05-23 12:57 UTC, vladimir-shirmanov commented on EducationPortal/BL/Services/UserService.cs
> +            var user = new MapperConfiguration(i => i.CreateMap<UserDTO, User>()).CreateMapper().Map<UserDTO, User>(data);
этого тут не должно быть

2021-05-23 13:06 UTC, vladimir-shirmanov requested changes
В целом довольно неплохо, но исправь замечания. Много вопросов к именованию. Так же почему то не везде используешь интерфейсы, хотя уже прикрутил ninject, не совсем понятно, то ли ты не до конца разобрался с DI то ли просто было лень писать доп интерфейсы

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/BL/Validators/Validator.cs
> +    public class Validator
какой то класс который делает все. Ты в него так и предполагаешь дальше накидывать методов валидации для всего приложения?

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/DL/DL.csproj
> +    <PackageReference Include="Ninject" Version="3.3.4" />
почему у тебя IoC контейнер на всех уровнях, зачем он тут нужен, если регистрация зависимостей происходит на UI уровне

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/DL/Infrastructure/Context.cs
> +    public class Context<T> : IContext<T> where T : class
почему это назывется context

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/DL/Interfaces/IRepository.cs
> +       // bool Update();
закоменченый код

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/DL/Repositories/UserRepository.cs
> +   public class UserRepository : IRepository<User>
а чем этот репозиторий будет отличатся от репозитория для курсов или материалов

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/Controllers/AuthorizationController.cs
> +    class AuthorizationController
почему это контроллер? где view в таком случае? не надо называть все контролерами что касается работы с пользовательским интерфейсом

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/Controllers/AuthorizationController.cs
> +        public AuthorizationController(UserService service)
почему тут конкретный класс

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/EducationPortal/users2.json
> +[{"Id":16,"Name":"123123","Email":"edfregrt12@gmail.com","Password":"09e31d1ab4de57a06dac4834a7cb1432"}]
это надо добавить в гитигнор

2021-05-23 13:06 UTC, vladimir-shirmanov commented on EducationPortal/userstest.json
> +[{"Id":71,"Name":"denis123","Email":"deonisij340@gmail.com","Password":"09e31d1ab4de57a06dac4834a7cb1432"}]
и это

2021-05-23 13:10 UTC, vladimir-shirmanov commented on EducationPortal/DL/Interfaces/IRepository.cs
> +   public  interface IRepository<T>
почему интерфейс репозитория находится в DAL

2021-05-24 08:20 UTC, unbrokable commented on EducationPortal/BL/Interfaces/IService.cs
> +    public interface IService<T>
Переименовал на более конкретный IServiceUser

2021-05-24 08:21 UTC, unbrokable commented on EducationPortal/BL/Services/UserService.cs
> +        public UserService(UserRepository bd, IHasher hasher)
Исправил
Добавил интерфейс для repository

2021-05-24 08:22 UTC, unbrokable commented on EducationPortal/BL/Services/UserService.cs
> +        Validator validator = new Validator();
Исправил 
Убрал валидатор и в UL установил fluentvalidation

2021-05-24 08:23 UTC, unbrokable commented on EducationPortal/BL/Services/UserService.cs
> +            var user = new MapperConfiguration(i => i.CreateMap<UserDTO, User>()).CreateMapper().Map<UserDTO, User>(data);
Добавил  интерфейс IMapperConfiguration

2021-05-24 08:23 UTC, unbrokable commented on EducationPortal/BL/Services/UserService.cs
> +            var user = new MapperConfiguration(i => i.CreateMap<UserDTO, User>()).CreateMapper().Map<UserDTO, User>(data);
Добавил интерфейс IMapperConfiguration

2021-05-24 08:23 UTC, unbrokable commented on EducationPortal/BL/Validators/Validator.cs
> +    public class Validator
Исправил
Убрал валидатор и в UL установил fluentvalidation

2021-05-24 08:24 UTC, unbrokable commented on EducationPortal/DL/DL.csproj
> +    <PackageReference Include="Ninject" Version="3.3.4" />
Исправил 
Убрал IoC контейнер в DL

2021-05-24 08:25 UTC, unbrokable commented on EducationPortal/DL/Infrastructure/Context.cs
> +    public class Context<T> : IContext<T> where T : class
Исправил
Переменовал

2021-05-24 08:25 UTC, unbrokable commented on EducationPortal/DL/Interfaces/IRepository.cs
> +       // bool Update();
Исправил
Убрал

2021-05-24 08:27 UTC, unbrokable commented on EducationPortal/DL/Repositories/UserRepository.cs
> +   public class UserRepository : IRepository<User>
Исправил
Сделал обобщенный repository для всех сущностей

2021-05-24 08:28 UTC, unbrokable commented on EducationPortal/EducationPortal/Controllers/AuthorizationController.cs
> +    class AuthorizationController
Исправил
Переименовал

2021-05-24 08:28 UTC, unbrokable commented on EducationPortal/EducationPortal/Controllers/AuthorizationController.cs
> +        public AuthorizationController(UserService service)
Исправил
Сделал интерфейсом

2021-05-24 08:29 UTC, unbrokable commented on EducationPortal/EducationPortal/users2.json
> +[{"Id":16,"Name":"123123","Email":"edfregrt12@gmail.com","Password":"09e31d1ab4de57a06dac4834a7cb1432"}]
Исправил 
убрал

2021-05-24 08:29 UTC, unbrokable commented on EducationPortal/userstest.json
> +[{"Id":71,"Name":"denis123","Email":"deonisij340@gmail.com","Password":"09e31d1ab4de57a06dac4834a7cb1432"}]
Исправил 
убрал

2021-05-24 08:36 UTC, unbrokable commented on EducationPortal/DL/Interfaces/IRepository.cs
> +   public  interface IRepository<T>
А где следует переместить IRepository?
В Bl я не могу так как он уже ссылается на DL. 
Надо еще создать один проект например Domain Layer?

2021-05-24 08:40 UTC, vladimir-shirmanov commented on EducationPortal/DL/Interfaces/IRepository.cs
> +   public  interface IRepository<T>
каким образом интерфейс женерик может ссылаться на DAL

2021-05-24 09:41 UTC, unbrokable commented on EducationPortal/DL/Interfaces/IRepository.cs
> +   public  interface IRepository<T>
Я поменял интерфейс что-бы он работал со всеми сущностями но реализацию и объявления в DAL
Если я перенесу интерфейс в BL то я не буду иметь к нему доступ в DAl 
и надо будет делать реализацию BL

2021-05-24 12:29 UTC, vladimir-shirmanov commented on EducationPortal/DL/Interfaces/IRepository.cs
> +   public  interface IRepository<T>
ок, то есть ты работаешь с 3-layer архитектурой классической. В таком случае, да такое возможно.

2021-05-24 12:30 UTC, vladimir-shirmanov commented on EducationPortal/DL/Interfaces/IRepository.cs
> +   public  interface IRepository<T>
но в таком случае у тебя каждый слой, жетско привязан к нижнему слою. Вот хорошее описание этой проблемы

> Одним из недостатков традиционного многослойного подхода является то, что обработка зависимостей во время компиляции осуществляется сверху вниз. Это значит, что слой пользовательского интерфейса зависит от слоя бизнес-логики, который, в свою очередь, зависит от слоя доступа к данным. Это значит, что слой бизнес-логики, который обычно содержит ключевые функции приложения, зависит от деталей реализации доступа к данным (и зачастую от наличия самой базы данных). Тестирование бизнес-логики в такой архитектуре зачастую затруднено и требует наличия тестовой базы данных.

2021-05-24 22:51 UTC, unbrokable commented on EducationPortal/DL/Interfaces/IRepository.cs
> +   public  interface IRepository<T>
Сделал "Onion архитектуру"(я надеюсь:) )
Добавил Domain 
Переместил  IRepository в DL

2021-05-25 11:50 UTC, vladimir-shirmanov approved these changes
мержи

2021-05-25 11:50 UTC, vladimir-shirmanov commented on EducationPortal/BL/Interfaces/IService.cs
> +    public interface IService<T>
так а где переименовал то, я до сих пор наблюдаю IService

2021-05-25 12:38 UTC, merged